version: '3'
services:
  nginx:
    build: ./nginx
    ports:
      - "80:80"
    links:
      - "php"
    volumes:
      - ./nginx/conf/default.conf:/etc/nginx/conf.d/default.conf
      - ../:/var/www
    networks:
      nn:
        ipv4_address: 192.168.5.100

  php:
    build: ./php
    ports:
      - "127.0.0.1:9000:9000"
    links:
      - "mysql"
      - "python"
    volumes:
      - ../:/var/www
    networks:
      nn:
        ipv4_address: 192.168.5.101

  mysql:
    build: ./mysql
    ports:
      - "127.0.0.1:3306:3306"
    volumes:
      - ./mysql/data/:/var/lib/mysql/
    environment:
      MYSQL_ROOT_PASSWORD: 123456
    networks:
      nn:
        ipv4_address: 192.168.5.102

  python:
    build: ./python
    ports:
      - "127.0.0.1:5678:5678"
    volumes:
      - ../public:/var/www/public
      - ../python_web:/var/www/python_web
    command: python3 /var/www/python_web/python_socket.py 192.168.5.103:5678
    networks:
      nn:
        ipv4_address: 192.168.5.103

  onlyoffice:
    build: ./onlyoffice
    ports:
      - "8000:80"
    environment:
      - JWT_ENABLED=false
    networks:
      nn:
        ipv4_address: 192.168.5.104
networks:
  nn:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 192.168.5.0/24
